# Generated by Django 5.0.6 on 2024-06-09 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('price_change', models.FloatField()),
                ('market_cap', models.IntegerField()),
                ('market_cap_rank', models.IntegerField()),
                ('volume', models.FloatField()),
                ('volume_rank', models.IntegerField()),
                ('volume_change', models.FloatField()),
                ('circulating_supply', models.IntegerField()),
                ('total_supply', models.IntegerField()),
                ('diluted_market_cap', models.IntegerField()),
                ('contracts', models.JSONField()),
                ('official_links', models.JSONField()),
                ('socials', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.AddField(
            model_name='coin',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.job'),
        ),
    ]
