# Generated by Django 5.0.6 on 2024-06-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_coin_job_delete_blogpost_coin_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='circulating_supply',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coin',
            name='diluted_market_cap',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coin',
            name='market_cap',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coin',
            name='total_supply',
            field=models.FloatField(),
        ),
    ]
