# Generated by Django 5.0.6 on 2024-06-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_coin_circulating_supply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='complete',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
