# Generated by Django 5.0.6 on 2024-06-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_job_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='complete',
            field=models.BooleanField(null=True),
        ),
    ]
